name: 'Serverless Action'
description: 'Serverless Action'
inputs:
  message:
    description: 'my message'
    required: true
    default: 'hello'
  enter:
    description: 'enter'
    required: true
    default: 'echo "hello from enter"'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.enter }}